fixes:
    - "ballerina/graphql/*/::../ballerina/"

ignore:
    - "ballerina-tests"
 chompiler-plugin"
    - "commons"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80
