[package]
org = "ballerina"
name = "graphql"
version = "@toml.version@"
authors = ["Ballerina"]
export=["graphql", "graphql.subgraph", "graphql.dataloader"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "@toml.version@"
path = "../native/build/libs/graphql-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-commons"
version = "@toml.version@"
path = "../commons/build/libs/graphql-commons-@project.version@.jar"
