[plugin]
id = "graphql-dimuthu-compiler-plugin"
class = "io.dimuthu.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/graphql-dimuthu-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../commons/build/libs/graphql-dimuthu-commons-@project.version@.jar"
