[package]
org = "dimuthu"
name = "graphql"
version = "1.11.6"
authors = ["Ballerina"]
export=["graphql", "graphql.subgraph", "graphql.dataloader"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.5"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "1.11.6"
path = "../native/build/libs/graphql-native-1.11.6-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-dimuthu-commons"
version = "1.11.6"
path = "../commons/build/libs/graphql-dimuthu-commons-1.11.6-SNAPSHOT.jar"
