[plugin]
id = "graphql-dimuthu-compiler-plugin"
class = "io.dimuthu.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/graphql-dimuthu-compiler-plugin-1.11.4-SNAPSHOT.jar"

[[dependency]]
path = "../commons/build/libs/graphql-dimuthu-commons-1.11.4-SNAPSHOT.jar"
